<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GbcNet.Tests.Integration</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.HangDump" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GbcNet.Core\GbcNet.Core.csproj" />
    <ProjectReference Include="..\..\src\GbcNet.App\GbcNet.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile
      Include="..\GbcNet.Tests.Shared\**\*.cs"
      Link="Shared\%(RecursiveDir)%(Filename)%(Extension)"
    />
  </ItemGroup>
</Project>
