version: 2
updates:
  - package-ecosystem: nuget
    directory: /emulator
    schedule:
      interval: weekly
    ignore:
      - dependency-name: Meziantou.Analyzer
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
