// <auto-generated />
using GbcNet.App.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GbcNet.App.Database.Migrations
{
    [DbContext(typeof(GbcNetDbContext))]
    partial class GbcNetDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("GbcNet.App.Database.Entities.LibraryRom", b =>
                {
                    b.Property<string>("RomHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("rom_hash");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("CartridgeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("cartridge_title");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_path");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("HardwareKind")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("hardware_kind");

                    b.Property<string>("LastKnownPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_known_path");

                    b.Property<string>("LastOpenedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_opened_at");

                    b.Property<int>("LaunchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("launch_count");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("RomHash");

                    b.HasIndex("LastKnownPath")
                        .IsUnique();

                    b.ToTable("roms", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
