<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageVersion Include="JetBrains.Annotations" Version="2026.2.0" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10" />
    <PackageVersion Include="ppy.SDL3-CS" Version="2026.722.0" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.3" />
    <PackageVersion Include="SoundFlow" Version="1.4.1" />
    <PackageVersion Include="ZstdSharp.Port" Version="0.8.8" />
  </ItemGroup>
  <ItemGroup Label="Testing">
    <PackageVersion Include="AwesomeAssertions" Version="9.5.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.9.0" />
    <PackageVersion Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup Label="Analyzers">
    <GlobalPackageReference
      Include="SonarAnalyzer.CSharp"
      Version="10.31.0.145097"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <GlobalPackageReference
      Include="Roslynator.Analyzers"
      Version="4.15.0"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
    <GlobalPackageReference
      Include="Meziantou.Analyzer"
      Version="3.0.125"
      PrivateAssets="all"
      IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive"
    />
  </ItemGroup>
</Project>
