<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>GbcNet.Tests.Unit</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AwesomeAssertions" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3.mtp-v2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\GbcNet.Core\GbcNet.Core.csproj" />
    <ProjectReference Include="..\..\src\GbcNet.App\GbcNet.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="RomTesting\Resources\**\*.gb" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="RomTesting\Resources\**\*.gbc" CopyToOutputDirectory="PreserveNewest" />
    <Content
      Include="RomTesting\Resources\**\*.dmgshade.bin"
      CopyToOutputDirectory="PreserveNewest"
    />
    <Content
      Include="RomTesting\Resources\**\*.rgb555le.bin"
      CopyToOutputDirectory="PreserveNewest"
    />
  </ItemGroup>

  <ItemGroup>
    <Compile
      Include="..\GbcNet.Tests.Shared\**\*.cs"
      Link="Shared\%(RecursiveDir)%(Filename)%(Extension)"
    />
  </ItemGroup>
</Project>
