// <auto-generated />
using GbcNet.App.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GbcNet.App.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GbcNetDbContext))]
    [Migration("20260731204458_AddCheatCodes")]
    partial class AddCheatCodes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("GbcNet.App.Entities.LibraryRom", b =>
                {
                    b.Property<string>("RomHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("rom_hash");

                    b.Property<string>("AddedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("CartridgeTitle")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("cartridge_title");

                    b.Property<string>("CoverPath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("cover_path");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("HardwareKind")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("hardware_kind");

                    b.Property<string>("LastKnownPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_known_path");

                    b.Property<string>("LastOpenedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("last_opened_at");

                    b.Property<int>("LaunchCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("launch_count");

                    b.Property<string>("NoIntroHash")
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("no_intro_hash");

                    b.Property<long>("PlayTimeTicks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L)
                        .HasColumnName("play_time_ticks");

                    b.Property<string>("UpdatedAt")
                        .IsRequired()
                        .HasMaxLength(33)
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("RomHash");

                    b.HasIndex("LastKnownPath")
                        .IsUnique();

                    b.ToTable("roms", (string)null);
                });

            modelBuilder.Entity("GbcNet.App.Entities.StoredCheatCode", b =>
                {
                    b.Property<string>("RomHash")
                        .HasColumnType("char(64)")
                        .HasColumnName("rom_hash");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(11)")
                        .HasColumnName("code");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(80)")
                        .HasColumnName("name");

                    b.HasKey("RomHash", "Type", "SortOrder");

                    b.HasIndex("RomHash", "Type", "Code")
                        .IsUnique();

                    b.ToTable("cheat_codes", null, t =>
                        {
                            t.HasCheckConstraint("CK_cheat_codes_is_enabled", "\"is_enabled\" IN (0, 1)");

                            t.HasCheckConstraint("CK_cheat_codes_name", "\"name\" IS NULL OR (length(\"name\") BETWEEN 1 AND 80 AND \"name\" = trim(\"name\"))");

                            t.HasCheckConstraint("CK_cheat_codes_sort_order", "\"sort_order\" BETWEEN 0 AND 19");

                            t.HasCheckConstraint("CK_cheat_codes_type", "\"type\" IN (0, 1)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
